# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! 
  Kindly note that this repository is maintained by [Vinit Shahdeo](https://www.linkedin.com/in/vinitshahdeo/). 
  He'll get back to you soon. Meanwhile check [this](https://github.com/vinitshahdeo/Hacktoberfest2020/) repo for more.
  
  [![Hacktoberfest2020](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=Hacktoberfest2020)](https://github.com/vinitshahdeo/Hacktoberfest2020)

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! ğŸ¤—
 Wishing you a great [Hacktoberfest 2020](https://dev.to/vinitshahdeo/hacktoberfest-2020-is-here-17op) ğŸ™Œ ğŸ‰ âš¡ï¸
 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/vinitshahdeo/Hacktoberfest2020/) repo.**
 
 [![Hacktoberfest2020](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=Hacktoberfest2020)](https://github.com/vinitshahdeo/Hacktoberfest2020)
 
 ğŸ“¢ Spread the word about [@vinitshahdeo/Hacktoberfest2020](https://github.com/vinitshahdeo/Hacktoberfest2020/) repo across your social media channels to help get others involved!
 **Give a shoutout to `DEV` [article](https://dev.to/vinitshahdeo/hacktoberfest-2020-is-here-17op)**. Retweet [this](https://twitter.com/Vinit_Shahdeo/status/1307339351764824064). 
 
 **Check out few other repos below** ğŸš€
 
 [![PortScanner](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=PortScanner)](https://github.com/vinitshahdeo/PortScanner) 
 [![SimpleBio](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=SimpleBio)](https://github.com/vinitshahdeo/SimpleBio) 
 [![HBD](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=HBD)](https://github.com/vinitshahdeo/HBD)
 [![Map Of India](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=Map-of-India)](https://github.com/vinitshahdeo/Map-of-India)
 
 
 **Show some â¤ï¸**
    - Consider leaving a â­ [here](https://github.com/vinitshahdeo/Hacktoberfest2020/).
    - Check out more beginner-friendly repos [here](https://github.com/vinitshahdeo/Hacktoberfest2020/blob/master/PROJECTS.md).
    - Follow @vinitshahdeo for more updates.
    - Read my open-source journey [here](https://www.opensourceforu.com/2020/07/if-you-are-a-techie-your-home-page-should-be-github-not-instagram/).
 
 #### Say Hi on [Twitter](https://twitter.com/Vinit_Shahdeo)! ğŸ‘‹
 
 [![Twitter Follow](https://img.shields.io/twitter/follow/Vinit_Shahdeo.svg?style=social)](https://twitter.com/Vinit_Shahdeo)
 
 PS: Please add @vinitshahdeo as a reviewer if you haven't added.
 

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
 Show some love by starring a few of my [repositories](https://github.com/vinitshahdeo?tab=repositories).
